### PR TITLE
Update concepts.tsv

### PR DESCRIPTION
**Pull request by IndianaTones**
I made the changes now but not sure how to handle those w/o concepts (new def's listed in new column)

### CODE REVIEW

**Review by LinguList — COMMENTED** [review]
There is some confusion about the fields.

The field Lexibank_GLOSS is meant to contain EXACTLY what we have in the column ENGLISH by now. The field ENGLISH can change, but you may want to keep capital letters. If ENGLISH changes, you need to revisit the concepticon mapping. 

Sorry if this wasn't clear from what I said before, but this is the way in which we preserve that edictor data does not need to be touched but can still be corrected ;)

So could you give it a new try? I see that changes are not many so it should hopefully be easy, and please correct the mappings, e.g., BREAKFAST is no longer a mapping to BREAKFEAST but ENGLISH will be GIVE BREAKFAST TO SOMEONE and the mapping should be deleted?

**Comment by IndianaTones** [comment]
Ok, hope this is right now and in the right place - essentially the changes mean a few empty concepts, correct?

**Review by LinguList — COMMENTED** [review]
Well, we still need the Lexibank_GLOSS field. This should contain the ORIGINAL Concept in concepticon which you had there ;)

**Comment by IndianaTones** [comment]
Ah right, ok, sorry for not understanding.

**Review by LinguList — APPROVED** [review]
Yes, that's what we need, thanks!

**Pull request merged**
